
#include "Raknet/MessageIdentifiers.h"

#ifndef GAME_MESSAGES_ENUMS
#define GAME_MESSAGES_ENUMS

enum GameMessages
{
	ID_GAME_MESSAGE_1 = ID_USER_PACKET_ENUM + 1,
	ID_SEND_MESSAGE = ID_USER_PACKET_ENUM + 2,
	ID_RECIEVE_MESSAGE = ID_USER_PACKET_ENUM + 3,
	ID_BROADCAST_USER = ID_USER_PACKET_ENUM + 4,
	ID_RECEIVE_BATTLESHIP_HIT_OR_MISS = ID_USER_PACKET_ENUM + 5,
	ID_RECEIVE_BATTLESHIP_SHOT = ID_USER_PACKET_ENUM + 6,
	ID_RECEIVE_TICTACTOE_FULL = ID_USER_PACKET_ENUM + 7,
	ID_RECEIVE_BATTLESHIP_FULL = ID_USER_PACKET_ENUM + 8,
	ID_SET_GAME_TYPE = ID_USER_PACKET_ENUM + 9,
	ID_SPECTATOR_REQUEST_DATA = ID_USER_PACKET_ENUM + 10,
	ID_RECEIVE_GAME_TYPE_FROM_HOST = ID_USER_PACKET_ENUM + 11
};

#endif
